const TIPO_INSTRUCCION = {
    PRINT: 'IMPRIMIR',
    DECLARACION: 'DECLARACION',
    ASIGNACION: 'ASIGNACION',
    AGREGACION: 'AGREGACION',
    WHILE: 'WHILE',
    FOR: 'FOR',
    DOWHILE: 'DO-WHILE',
    IF: 'IF',
    IF_ELSE: 'IF-ELSE',
    ELSE_IF: 'ELSE-IF',
    CASO: 'CASO-SWITCH',
    SWITCH: 'SWITCH'
}

module.exports = TIPO_INSTRUCCION