const TIPO_INSTRUCCION = {
    PRINT: 'IMPRIMIR',
    DECLARACION: 'DECLARACION',
    ASIGNACION: 'ASIGNACION',
    AGREGACION: 'AGREGACION',
    WHILE: 'WHILE',
    FOR: 'FOR'
}

module.exports = TIPO_INSTRUCCION