const TIPO_INSTRUCCION = {
    PRINT: 'IMPRIMIR',
    DECLARACION: 'DECLARACION',
    ASIGNACION: 'ASIGNACION',
    AGREGACION: 'AGREGACION',
    WHILE: 'WHILE',
    FOR: 'FOR',
    DOWHILE: 'DO-WHILE',
    IF: 'IF',
    IF_ELSE: 'IF-ELSE',
    ELSE_IF: 'ELSE-IF',
    CASO: 'CASO-SWITCH',
    SWITCH: 'SWITCH',
    TERNARIO: 'OPERADOR-TERNARIO',
    CASTEO: 'CASTEO',
    ACCESO: 'ACCESO-EDD',
    BREAK: 'TRANSFERENCIA-BREAK',
    CONTINUE: 'TRANSFERENCIA-CONTINUE',
    TO_LOWER: 'TO-LOWER',
    TO_UPPER: 'TO-UPPER',
    LENGTH: 'LENGTH',
    TRUNCATE: 'TRUNCATE',
    ROUND: 'ROUND',
    TYPEOF: 'TYPEOF',
    TOSTRING: 'TOSTRING',
    TOCHARLIST: 'TOCHARARRAY',
    

}

module.exports = TIPO_INSTRUCCION